name: Matrix Calculator Java

on:
  push:
    branches:
      - main  
jobs:
  test: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
    
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2
    
      - name: Run Tests
        run: mvn -X test

  build:
    runs-on: ubuntu-latest
    needs: test 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build JAR file
        run: mvn package

      - name: List target directory
        run: ls -R target

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Set environment variable to disable BuildKit
        run: echo "DOCKER_BUILDKIT=0" >> $GITHUB_ENV
        
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/matrix-calculator:latest -f docker/Dockerfile .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/matrix-calculator:latest

      - name: Log in to Render
        uses: sws2apps/render-deployment@main
        with:
          serviceId: ${{ secrets.RENDER_SERVICE_ID }}
          apiKey: ${{ secrets.RENDER_API_KEY }}
          multipleDeployment: false 
      
    
        
